#ifndef __EXCEPTIONS_TYPE_H_
#define __EXCEPTIONS_TYPE_H_

typedef enum Exception_t
{
    NO_EXCEPTION,
    STACK_OVERFLOW_EXCEPTION,
    STACK_UNDERFLOW_EXCEPTION,
    INVALID_ARGUMENT_EXCEPTION,
    NULL_POINTER_ARGUMENT_EXCEPTION,
    MEMORY_ALLOCATION_FAILURE_EXCEPTION
} Exception_t;

#endif // __EXCEPTIONS_TYPE_H_